/-
Copyright 2025 The Gromov Project Authors.
SPDX-License-Identifier: Apache-2.0

Finitely generated abelian groups and their polycyclic structure.
-/

import Gromov.Proofs.Polycyclic.Core

/-!
# Finitely Generated Abelian Groups and Polycyclic Structure

This file develops the connection between finitely generated abelian groups and
polycyclic groups, which is crucial for proving that f.g. nilpotent groups are polycyclic.

## Main Results

* `isPolycyclic_of_fg_commGroup`: Finitely generated abelian groups are polycyclic.
  This follows from the structure theorem: every f.g. abelian group is isomorphic to
  Z^r x T where T is a finite abelian group.

* `fg_abelian_structure`: The structure theorem for f.g. abelian groups (Z^r x finite).

* `lowerCentralSeries_quotient_fg`: Quotients G_i/G_{i+1} in the lower central series
  of a f.g. nilpotent group are finitely generated.

* `lowerCentralSeries_quotient_comm`: Quotients G_i/G_{i+1} in the lower central series
  are abelian (they are central in G/G_{i+1}).

## Mathematical Background

The lower central series of a group G is defined by:
- G_0 = G
- G_{i+1} = [G, G_i] (the commutator subgroup)

For nilpotent groups, this series terminates at 1 after finitely many steps.
The quotients G_i/G_{i+1} are abelian because G_{i+1} = [G, G_i] contains all
commutators of elements from G and G_i.

## References

* Segal, D. "Polycyclic Groups" Cambridge University Press (1983), Chapter 1
* Robinson, D.J.S. "A Course in the Theory of Groups" 2nd ed. (1996), Theorem 5.4.12
* Lang, S. "Algebra" 3rd ed. (2002), Chapter I, Section 10 (Structure theorem)
-/

open Subgroup Group

namespace Group

variable {G : Type*} [Group G]

/-! ### Structure Theorem for Finitely Generated Abelian Groups -/

-- Note: isPolycyclic_of_fg_commGroup is defined in Core.lean and imported here.
-- See Core.lean for the theorem: Finitely generated abelian groups are polycyclic.

/-- The structure theorem for finitely generated abelian groups.

Every finitely generated abelian group is isomorphic to Z^r x T where:
- r is the rank (number of infinite cyclic factors)
- T is a finite abelian group (the torsion subgroup)

This is a fundamental result in algebra. The torsion subgroup T can be further
decomposed as a product of cyclic groups of prime power order.

Note: This theorem requires significant infrastructure from Mathlib's module theory
and linear algebra. We state it here for completeness but the proof relies on
the classification of finitely generated modules over a PID.

References:
- Lang, S. "Algebra" 3rd ed. (2002), Chapter I, Theorem 10.3
- Hungerford, T. "Algebra" (1974), Theorem 2.1
-/
theorem fg_abelian_structure (H : Type*) [CommGroup H] [FG H] :
    ∃ (r : Nat) (T : Type*) (_ : CommGroup T) (_ : Finite T),
      Nonempty (H ≃* (Fin r → Multiplicative ℤ) × T) := by
  -- This is the fundamental structure theorem for f.g. abelian groups.
  -- The proof requires:
  -- 1. View H as a ℤ-module (via Additive H)
  -- 2. Apply the structure theorem for f.g. modules over PIDs
  -- 3. ℤ is a PID, so Additive H ≃ ℤ^r ⊕ ⨁ᵢ ℤ/nᵢℤ
  -- 4. The torsion part T = ⨁ᵢ ℤ/nᵢℤ is finite
  -- 5. Convert back to multiplicative notation
  -- This requires Mathlib's Module.equiv_directSum_of_isTorsion and related machinery.
  -- We defer to Mathlib's AddCommGroup.equiv_free_prod_directSum_zmod or similar.
  sorry

/-! ### Lower Central Series Quotients -/

/-- Quotients G_i/G_{i+1} in the lower central series of a f.g. nilpotent group
are finitely generated.

For a f.g. nilpotent group G, each quotient in the lower central series is
f.g. abelian. The proof uses that:
1. G is f.g., so G/G_1 = G/[G,G] is f.g. abelian
2. For i > 0, G_i/G_{i+1} is generated by commutators [g, x] where g ∈ G and x ∈ G_{i-1}
3. Since G and G_{i-1} are f.g. (by induction), there are finitely many such commutators

References:
- Robinson, D.J.S. "A Course in the Theory of Groups" 2nd ed. (1996), Lemma 5.2.17
- Hall, P. "The Edmonton Notes on Nilpotent Groups" (1957)
-/
theorem lowerCentralSeries_quotient_fg (H : Type*) [Group H] [FG H] [IsNilpotent H]
    (i : Nat) (_hi : i < Group.nilpotencyClass H) :
    FG (lowerCentralSeries H i ⧸
      (lowerCentralSeries H (i + 1)).subgroupOf (lowerCentralSeries H i)) := by
  -- In a f.g. nilpotent group, all subgroups are f.g. (Mal'cev)
  -- This follows from polycyclicity + Mal'cev's theorem
  have hpoly : IsPolycyclic H := isPolycyclic_of_isNilpotent_fg H
  -- Subgroup.fg_of_polycyclic gives us FG ↥(lowerCentralSeries H i) directly
  haveI : FG (lowerCentralSeries H i) := Subgroup.fg_of_polycyclic hpoly (lowerCentralSeries H i)
  -- The quotient of a f.g. group by a normal subgroup is f.g.
  exact QuotientGroup.fg _

/-- Quotients G_i/G_{i+1} in the lower central series are abelian.

The lower central series quotient G_i/G_{i+1} is abelian because G_{i+1} = [G, G_i]
contains all commutators. More precisely, for any x, y in G_i, the commutator
[x, y] = x^{-1}y^{-1}xy is in [G_i, G_i] ⊆ [G, G_i] = G_{i+1}.

In fact, G_i/G_{i+1} is central in G/G_{i+1}, which is a stronger statement.

References:
- Segal, D. "Polycyclic Groups" (1983), Chapter 1
- Robinson, D.J.S. "A Course in the Theory of Groups" 2nd ed. (1996), Section 5.1
-/
theorem lowerCentralSeries_quotient_comm (H : Type*) [Group H] (i : Nat) :
    ∀ x y : (lowerCentralSeries H i ⧸
      (lowerCentralSeries H (i + 1)).subgroupOf (lowerCentralSeries H i)),
        x * y = y * x := by
  intro x y
  -- Lift x and y to representatives in lowerCentralSeries H i
  induction x using Quotient.inductionOn with | h x =>
  induction y using Quotient.inductionOn with | h y =>
  -- Need to show (xy)⁻¹(yx) ∈ G_{i+1}, which follows from [y⁻¹, x⁻¹] ∈ G_{i+1}
  simp only [← QuotientGroup.mk_mul]
  rw [QuotientGroup.eq]
  -- (x * y)⁻¹ * (y * x) = y⁻¹ * x⁻¹ * y * x = ⁅y⁻¹, x⁻¹⁆
  -- Since y⁻¹ ∈ G_i ⊆ G and x⁻¹ ∈ G_i, we have ⁅y⁻¹, x⁻¹⁆ ∈ [G, G_i] = G_{i+1}
  have hcomm : ⁅(y : H)⁻¹, (x : H)⁻¹⁆ ∈ lowerCentralSeries H (i + 1) := by
    rw [lowerCentralSeries_succ]
    apply Subgroup.commutator_mem_commutator
    · exact (lowerCentralSeries H i).inv_mem y.property
    · exact Subgroup.mem_top (x : H)⁻¹
  -- Convert to the subgroupOf membership
  rw [Subgroup.mem_subgroupOf]
  convert hcomm using 1
  simp only [Subgroup.coe_mul, Subgroup.coe_inv, mul_inv_rev, inv_inv, commutatorElement_def]
  group

/-- The quotient G_i/G_{i+1} is central in G/G_{i+1}.

This is a strengthening of `lowerCentralSeries_quotient_comm`. Not only is G_i/G_{i+1}
abelian, but it is in the center of G/G_{i+1}. This is because for any g ∈ G and
x ∈ G_i, the commutator [g, x] is in G_{i+1} by definition of the lower central series.

This centrality property is what makes the lower central series useful for
understanding nilpotent groups.
-/
theorem lowerCentralSeries_quotient_central (H : Type*) [Group H] (i : Nat) :
    (lowerCentralSeries H i).map (QuotientGroup.mk' (lowerCentralSeries H (i + 1))) ≤
      Subgroup.center (H ⧸ lowerCentralSeries H (i + 1)) := by
  -- An element is central iff it commutes with all elements
  intro x hx
  rw [Subgroup.mem_center_iff]
  intro g
  -- x is the image of some x' ∈ G_i
  obtain ⟨x', hx', rfl⟩ := Subgroup.mem_map.mp hx
  -- g is some element of G/G_{i+1}; lift it
  induction g using Quotient.inductionOn with | h g =>
  -- Need: g * x' = x' * g in the quotient, i.e., (g * x')⁻¹ * (x' * g) ∈ G_{i+1}
  simp only [QuotientGroup.mk'_apply, ← QuotientGroup.mk_mul]
  rw [QuotientGroup.eq]
  -- (g * x')⁻¹ * (x' * g) = x'⁻¹ * g⁻¹ * x' * g = ⁅x'⁻¹, g⁻¹⁆
  -- Since x'⁻¹ ∈ G_i and g⁻¹ ∈ G, we have ⁅x'⁻¹, g⁻¹⁆ ∈ [G_i, G] = G_{i+1}
  have hcomm : ⁅x'⁻¹, g⁻¹⁆ ∈ lowerCentralSeries H (i + 1) := by
    rw [lowerCentralSeries_succ]
    apply Subgroup.commutator_mem_commutator
    · exact (lowerCentralSeries H i).inv_mem hx'
    · exact Subgroup.mem_top g⁻¹
  convert hcomm using 1
  simp only [commutatorElement_def]
  group

end Group
