/-
Copyright 2025 The Gromov Project Authors.
SPDX-License-Identifier: Apache-2.0

Finitely generated abelian groups and their polycyclic structure.
-/

import Gromov.Proofs.Polycyclic.Core

set_option linter.style.emptyLine false
set_option linter.style.longLine false

/-!
# Finitely Generated Abelian Groups and Polycyclic Structure

This file develops the connection between finitely generated abelian groups and
polycyclic groups, which is crucial for proving that f.g. nilpotent groups are polycyclic.

## Main Results

* `isPolycyclic_of_fg_commGroup`: Finitely generated abelian groups are polycyclic.
  This follows from the structure theorem: every f.g. abelian group is isomorphic to
  Z^r x T where T is a finite abelian group.

* `fg_abelian_structure`: The structure theorem for f.g. abelian groups (Z^r x finite).

* `lowerCentralSeries_quotient_fg`: Quotients G_i/G_{i+1} in the lower central series
  of a f.g. nilpotent group are finitely generated.

* `lowerCentralSeries_quotient_comm`: Quotients G_i/G_{i+1} in the lower central series
  are abelian (they are central in G/G_{i+1}).

## Mathematical Background

The lower central series of a group G is defined by:
- G_0 = G
- G_{i+1} = [G, G_i] (the commutator subgroup)

For nilpotent groups, this series terminates at 1 after finitely many steps.
The quotients G_i/G_{i+1} are abelian because G_{i+1} = [G, G_i] contains all
commutators of elements from G and G_i.

## References

* Segal, D. "Polycyclic Groups" Cambridge University Press (1983), Chapter 1
* Robinson, D.J.S. "A Course in the Theory of Groups" 2nd ed. (1996), Theorem 5.4.12
* Lang, S. "Algebra" 3rd ed. (2002), Chapter I, Section 10 (Structure theorem)
-/

open Subgroup Group

namespace Group

variable {G : Type*} [Group G]

/-! ### Structure Theorem for Finitely Generated Abelian Groups -/

/-- Finitely generated abelian groups are polycyclic.

The proof uses the structure theorem for finitely generated abelian groups:
every f.g. abelian group is isomorphic to Z^r x T where T is a finite abelian group.
- Z^r is polycyclic: use the standard basis to get a series Z^r > Z^{r-1} > ... > Z > 1
  with cyclic quotients (each isomorphic to Z).
- T is finite and abelian (hence solvable), so T is polycyclic.
- The product of polycyclic groups is polycyclic (concatenate the series).

References:
- Segal, D. "Polycyclic Groups" (1983), Corollary 1.1
- Robinson, D.J.S. "A Course in the Theory of Groups" 2nd ed. (1996), Theorem 5.4.12
-/
theorem isPolycyclic_of_fg_commGroup (H : Type*) [CommGroup H] [FG H] :
    IsPolycyclic H := by
  -- Proof strategy:
  -- 1. Apply the structure theorem: H ≅ Z^r × T for some r and finite T
  -- 2. Z^r is polycyclic (induction on r, Z is cyclic)
  -- 3. T is finite abelian, hence polycyclic (finite solvable groups are polycyclic)
  -- 4. Products of polycyclic groups are polycyclic
  sorry

/-- The structure theorem for finitely generated abelian groups.

Every finitely generated abelian group is isomorphic to Z^r x T where:
- r is the rank (number of infinite cyclic factors)
- T is a finite abelian group (the torsion subgroup)

This is a fundamental result in algebra. The torsion subgroup T can be further
decomposed as a product of cyclic groups of prime power order.

References:
- Lang, S. "Algebra" 3rd ed. (2002), Chapter I, Theorem 10.3
- Hungerford, T. "Algebra" (1974), Theorem 2.1
-/
theorem fg_abelian_structure (H : Type*) [CommGroup H] [FG H] :
    ∃ (r : Nat) (T : Type*) (_ : CommGroup T) (_ : Finite T),
      Nonempty (H ≃* (Fin r → Multiplicative Int) × T) := by
  -- Proof strategy:
  -- 1. Take a finite generating set S for H
  -- 2. Consider the free abelian group Z^|S| with surjection onto H
  -- 3. The kernel K is a subgroup of Z^|S|, hence free abelian of rank ≤ |S|
  -- 4. Use Smith normal form to get the structure
  -- 5. The torsion part is finite, the free part has rank r = |S| - rank(K)
  sorry

/-! ### Lower Central Series Quotients -/

/-- Quotients G_i/G_{i+1} in the lower central series of a f.g. nilpotent group
are finitely generated.

For a f.g. nilpotent group G, each quotient in the lower central series is
f.g. abelian. The proof uses that:
1. G is f.g., so G/G_1 = G/[G,G] is f.g. abelian
2. For i > 0, G_i/G_{i+1} is generated by commutators [g, x] where g ∈ G and x ∈ G_{i-1}
3. Since G and G_{i-1} are f.g. (by induction), there are finitely many such commutators

References:
- Robinson, D.J.S. "A Course in the Theory of Groups" 2nd ed. (1996), Lemma 5.2.17
- Hall, P. "The Edmonton Notes on Nilpotent Groups" (1957)
-/
theorem lowerCentralSeries_quotient_fg (H : Type*) [Group H] [FG H] [IsNilpotent H]
    (i : Nat) (hi : i < Group.nilpotencyClass H) :
    FG (lowerCentralSeries H i ⧸ (lowerCentralSeries H (i + 1)).subgroupOf (lowerCentralSeries H i)) := by
  -- Proof strategy:
  -- 1. The quotient G_i/G_{i+1} is abelian (see lowerCentralSeries_quotient_comm)
  -- 2. G_i is f.g. (subgroups of f.g. nilpotent groups are f.g.)
  -- 3. Quotients of f.g. groups are f.g.
  sorry

/-- Quotients G_i/G_{i+1} in the lower central series are abelian.

The lower central series quotient G_i/G_{i+1} is abelian because G_{i+1} = [G, G_i]
contains all commutators. More precisely, for any x, y in G_i, the commutator
[x, y] = x^{-1}y^{-1}xy is in [G_i, G_i] ⊆ [G, G_i] = G_{i+1}.

In fact, G_i/G_{i+1} is central in G/G_{i+1}, which is a stronger statement.

References:
- Segal, D. "Polycyclic Groups" (1983), Chapter 1
- Robinson, D.J.S. "A Course in the Theory of Groups" 2nd ed. (1996), Section 5.1
-/
theorem lowerCentralSeries_quotient_comm (H : Type*) [Group H] (i : Nat) :
    ∀ x y : (lowerCentralSeries H i ⧸ (lowerCentralSeries H (i + 1)).subgroupOf (lowerCentralSeries H i)),
      x * y = y * x := by
  -- Proof strategy:
  -- 1. For x, y in G_i, we need [x, y] ∈ G_{i+1}
  -- 2. By definition, G_{i+1} = [G, G_i] = ⟨[g, h] : g ∈ G, h ∈ G_i⟩
  -- 3. Since x, y ∈ G_i ⊆ G, we have [x, y] ∈ [G_i, G_i] ⊆ [G, G_i] = G_{i+1}
  -- 4. Hence x * y * (y * x)^{-1} = [x, y] ∈ G_{i+1}, so x * y = y * x in the quotient
  sorry

/-- The quotient G_i/G_{i+1} is central in G/G_{i+1}.

This is a strengthening of `lowerCentralSeries_quotient_comm`. Not only is G_i/G_{i+1}
abelian, but it is in the center of G/G_{i+1}. This is because for any g ∈ G and
x ∈ G_i, the commutator [g, x] is in G_{i+1} by definition of the lower central series.

This centrality property is what makes the lower central series useful for
understanding nilpotent groups.
-/
theorem lowerCentralSeries_quotient_central (H : Type*) [Group H] (i : Nat) :
    (lowerCentralSeries H i).map (QuotientGroup.mk' (lowerCentralSeries H (i + 1))) ≤
      center (H ⧸ lowerCentralSeries H (i + 1)) := by
  -- Proof strategy:
  -- 1. For x ∈ G_i and g ∈ G, we need [g, x] ∈ G_{i+1}
  -- 2. This is exactly the definition: G_{i+1} = [G, G_i]
  -- 3. Hence gxg^{-1}x^{-1} ∈ G_{i+1}, so gx = xg in G/G_{i+1}
  sorry

end Group
