/-
Copyright 2025 The Gromov Project Authors.
SPDX-License-Identifier: Apache-2.0

Definitions for virtually nilpotent groups and related properties.
-/

module

public import Mathlib.GroupTheory.Nilpotent
public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.QuotientGroup.Basic

namespace Group

@[expose] public section

variable {G : Type*} [Group G]

/-! ## Polycyclic Groups

A polycyclic group has a subnormal series with cyclic quotients.
-/

/-- A quotient of subgroups H ⊆ K is cyclic if it's generated by a single element. -/
def QuotientIsCyclic {G : Type*} [Group G] (H K : Subgroup G)
    (_ : H ≤ K) (_ : (H.subgroupOf K).Normal) : Prop :=
  ∃ g : K, Subgroup.zpowers (QuotientGroup.mk (s := H.subgroupOf K) g) = ⊤

/-- A group is polycyclic if it has a subnormal series with cyclic factors.
A group G is polycyclic if there exists a finite chain of subgroups
G = G_0 ⊇ G_1 ⊇ ... ⊇ G_n = {1} such that each G_i is normal in G_{i-1}
and each quotient G_{i-1}/G_i is cyclic.

Note: This is equivalent to G being a solvable group with all factors cyclic,
which is also equivalent to G being finitely generated and virtually nilpotent
(the latter is a deep theorem of Mal'cev). -/
def IsPolycyclic (G : Type*) [Group G] : Prop :=
  ∃ (n : ℕ) (H : Fin (n + 1) → Subgroup G),
    H 0 = ⊤ ∧ H ⟨n, Nat.lt_succ_self n⟩ = ⊥ ∧
    (∀ i : Fin n, H i.succ ≤ H i.castSucc) ∧
    (∀ i : Fin n, ((H i.succ).subgroupOf (H i.castSucc)).Normal) ∧
    (∀ i : Fin n, (h1 : H i.succ ≤ H i.castSucc) →
      (h2 : ((H i.succ).subgroupOf (H i.castSucc)).Normal) →
      QuotientIsCyclic (H i.succ) (H i.castSucc) h1 h2)

/-! ## Residually Finite Groups -/

/-- A group is residually finite if the intersection of all finite-index normal subgroups
is trivial. Equivalently, for every non-identity element g, there is a finite quotient
in which g is non-trivial. -/
def IsResiduallyFinite (G : Type*) [Group G] : Prop :=
  ∀ g : G, g ≠ 1 → ∃ N : Subgroup G, N.Normal ∧ N.FiniteIndex ∧ g ∉ N

/-! ## Virtual Nilpotency Class -/

/-- Helper predicate: G has a finite-index nilpotent subgroup of nilpotency class at most n. -/
def HasNilpotentSubgroupOfClassLE (G : Type*) [Group G] (n : ℕ) : Prop :=
  ∃ N : Subgroup G, ∃ (_ : IsNilpotent N), N.FiniteIndex ∧ @Group.nilpotencyClass N _ ‹_› ≤ n

/-- The virtual nilpotency class of a group is the minimum nilpotency class among all
finite-index nilpotent subgroups. Returns 0 if the group is not virtually nilpotent. -/
noncomputable def virtualNilpotencyClass (G : Type*) [Group G] : ℕ := by
  classical
  exact if h : IsVirtuallyNilpotent G then
    Nat.find (show ∃ n : ℕ, HasNilpotentSubgroupOfClassLE G n by
      obtain ⟨N, hNil, hFin⟩ := h
      exact ⟨@Group.nilpotencyClass N _ hNil, N, hNil, hFin, le_refl _⟩)
  else 0

end

end Group
