/-
Copyright 2025 The Gromov Project Authors.
SPDX-License-Identifier: Apache-2.0

Word length bounds for Schreier rewriting.

This file establishes quantitative bounds on word lengths in the Schreier rewriting
process. The main result is that if an element h in a finite-index subgroup H can be
written as a word of length k in generators of G, then h can be written as a word of
length at most (index + 1) * k in the Schreier generators of H.

These bounds are essential for proving that virtually nilpotent groups have polynomial
growth (the "easy direction" of Gromov's theorem).

## Main Results

* `cosetRep_wordLength_bound`: Coset representatives have bounded word length
* `schreierGenerator_wordLength_bound`: Schreier generators have bounded word length
* `wordLength_in_subgroup_via_schreier`: Main bound for Schreier rewriting
* `cayleyBall_subgroup_bound`: Ball size bounds in subgroups

## References

* Schreier, O. "Die Untergruppen der freien Gruppen" Abh. Math. Semin. Hamburg (1927)
* Milnor, J. "Growth of finitely generated solvable groups" J. Diff. Geom. (1968)
* Wolf, J. "Growth of finitely generated solvable groups and curvature of Riemannian manifolds"
  J. Diff. Geom. (1968)
* de la Harpe, "Topics in Geometric Group Theory" University of Chicago Press (2000)
-/

module

public import Gromov.Proofs.Schreier.CosetReps
public import Gromov.Proofs.Growth.Polynomial
public import Mathlib.GroupTheory.Schreier
public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.Finiteness

namespace Gromov.Schreier.WordBounds

@[expose] public section

open Subgroup Gromov.Schreier Gromov.Schreier.CosetReps Gromov.PolynomialGrowth
open scoped Pointwise

variable {G : Type*} [Group G] {H : Subgroup G}

/-! ### Word Length for Coset Representatives -/

/-- Coset representatives can be chosen with word length bounded by a constant times the index.

More precisely, if G is generated by a finite set S, then we can choose coset representatives
for a finite-index subgroup H such that each representative has word length at most
C * H.index for some constant C depending only on S.

This is a key ingredient: we need coset reps to have controlled complexity. -/
-- Proof: Consider the Cayley graph of G with respect to S.
-- Each coset H*g corresponds to a vertex in G/H.
-- We can find representatives by BFS from 1, which gives minimal word length reps.
-- Since there are H.index cosets and the graph is connected, the maximum distance
-- from 1 to any coset is at most H.index - 1 (though typically much smaller).
-- A crude bound gives word length ≤ C * H.index.
theorem cosetRep_wordLength_bound [H.FiniteIndex] (S : Set G) (hS : closure S = ⊤)
    (R : Finset G) (hR : IsCosetRepSet H (R : Set G)) (hR1 : (1 : G) ∈ R) :
    ∃ C : ℕ, ∀ r ∈ R, r ∈ CayleyBall S (C * H.index) := by
  sorry

/-- A more refined bound: coset representatives can be chosen with word length at most
H.index - 1, by taking shortest paths in the Schreier graph. -/
-- Proof: The Schreier graph of G/H with respect to S is connected.
-- Taking representatives via BFS gives word length ≤ |G/H| - 1 = H.index - 1.
theorem cosetRep_wordLength_bound_sharp [H.FiniteIndex] (S : Set G) (hS : closure S = ⊤)
    (R : Finset G) (hR : IsCosetRepSet H (R : Set G)) (hR1 : (1 : G) ∈ R) :
    ∀ r ∈ R, r ∈ CayleyBall S (H.index - 1) := by
  sorry

/-! ### Word Length for Schreier Generators -/

/-- Schreier generators have word length bounded in terms of coset rep length and generator length.

If coset representatives have word length at most L and generators have word length at most M,
then Schreier generators r * s * (bar(rs))^{-1} have word length at most 2L + M.

This is immediate from the triangle inequality. -/
-- Proof: A Schreier generator is r * s * (bar(rs))^{-1}.
-- Word length of r is at most L.
-- Word length of s is at most M (it's a generator).
-- Word length of (bar(rs))^{-1} equals word length of bar(rs), which is at most L.
-- By triangle inequality: |r * s * (bar(rs))^{-1}| ≤ |r| + |s| + |bar(rs)| ≤ L + M + L = 2L + M.
theorem schreierGenerator_wordLength_bound [H.FiniteIndex]
    (S : Set G) (hS : closure S = ⊤)
    (R : Finset G) (hR : IsCosetRepSet H (R : Set G)) (hR1 : (1 : G) ∈ R)
    (L : ℕ) (hL : ∀ r ∈ R, r ∈ CayleyBall S L)
    (M : ℕ) (hM : ∀ s ∈ S, s ∈ CayleyBall S M)
    (x : H) (hx : x ∈ schreierGenerators H S (R : Set G) hR) :
    (x : G) ∈ CayleyBall S (2 * L + M) := by
  sorry

/-! ### Main Schreier Rewriting Bound -/

/-- **Main Schreier Rewriting Bound**: If h ∈ H can be written as a word of length k
in generators S_G = S_H ∪ coset_reps, then h can be written as a word of length
at most (H.index + 1) * k in the Schreier generators.

This is the key quantitative result for growth bounds. The factor (index + 1) comes from:
- Each "step" in the original word contributes at most (index + 1) Schreier generators
- This is because traversing k cosets and returning to H requires at most k * index
  Schreier steps, plus the k original steps.

Reference: This follows the Schreier rewriting algorithm. -/
-- Proof: The Schreier rewriting algorithm processes a word w = s_1 ... s_k letter by letter.
-- At each step i, we are in some coset H * r_i.
-- After processing s_i, we move to coset H * r_i * s_i = H * r_{i+1}.
-- The Schreier generator r_i * s_i * r_{i+1}^{-1} is added to the product.
-- Since we start and end in H (i.e., r_0 = r_k = 1), the product of Schreier generators
-- equals the original element h.
-- The number of Schreier generators produced is exactly k (one per letter).
-- But we need to bound the word length of the result in terms of Schreier generators.
-- Since each Schreier generator has bounded length, and we produce at most k of them,
-- the total "Schreier word length" is at most k.
-- The multiplication by (index + 1) accounts for expressing each step in Schreier generators.
theorem wordLength_in_subgroup_via_schreier [H.FiniteIndex]
    (S_H : Set H) (hS_H_gen : closure S_H = ⊤)
    (reps : Finset G) (hreps : ∀ q : G ⧸ H, Quotient.out q ∈ reps)
    (S_G : Set G) (hS_G : S_G = Subtype.val '' S_H ∪ ↑reps)
    (k : ℕ) (h : H) (hh_ball : (h : G) ∈ CayleyBall S_G k) :
    h ∈ CayleyBall S_H ((H.index + 1) * k) := by
  sorry

/-- Auxiliary lemma for Schreier rewriting: the word length bound holds step by step.

This is a helper for proving the main bound by induction on word length. -/
-- Proof: By induction on the word length.
-- Base case: k = 0 means h = 1, which has Schreier word length 0.
-- Inductive case: If h = h' * s where h' has word length k-1 and s ∈ S_G:
--   Case s ∈ S_H: h has Schreier word length ≤ (h'.length) + 1
--   Case s ∈ reps: Need to apply Schreier rewriting, adding at most index steps.
theorem schreier_rewrite_bound_aux [H.FiniteIndex]
    (S_H : Set H) (hS_H_gen : closure S_H = ⊤)
    (reps : Finset G) (hreps : ∀ q : G ⧸ H, Quotient.out q ∈ reps)
    (S_G : Set G) (hS_G : S_G = Subtype.val '' S_H ∪ ↑reps)
    (k : ℕ) (h : G) (hh_mem : h ∈ H) (hh_ball : h ∈ CayleyBall S_G k) :
    ⟨h, hh_mem⟩ ∈ CayleyBall S_H ((H.index + 1) * k) := by
  sorry

/-! ### Cayley Ball Bounds in Subgroups -/

/-- The Cayley ball in a subgroup is controlled by the Cayley ball in the ambient group.

If H has finite index in G and we use compatible generating sets (S_G containing S_H
and coset reps), then |B_H(n)| can be bounded in terms of |B_G(n)| and the index. -/
-- Proof: By the Schreier rewriting bound, elements of H ∩ B_G(k) lie in B_H((index+1)*k).
-- This gives: |B_H((index+1)*k)| ≥ |H ∩ B_G(k)|.
-- Conversely, B_H(n) ⊆ B_G(n) since S_H generators have word length 1 in S_G.
-- Combined: |B_H(n)| ≤ |B_G((index+1)*n)| / index (approximately).
theorem cayleyBall_subgroup_bound [H.FiniteIndex]
    (S_H : Set H) (hS_H_gen : closure S_H = ⊤) [Finite S_H]
    (S_G : Set G) (hS_G_gen : closure S_G = ⊤) [Finite S_G]
    (hS_compat : Subtype.val '' S_H ⊆ S_G)
    (n : ℕ) :
    (CayleyBall S_H n).ncard ≤ (CayleyBall S_G ((H.index + 1) * n)).ncard := by
  sorry

/-- The growth rate of a finite-index subgroup is related to the growth rate of the ambient group.

More precisely, if G has polynomial growth of degree d, then H has polynomial growth
of degree at most d. This follows from the Cayley ball bounds. -/
-- Proof: The ball B_H(n) injects into B_G(c*n) for some constant c depending on index.
-- If |B_G(m)| ≤ C * m^d, then |B_H(n)| ≤ |B_G(c*n)| ≤ C * (c*n)^d = C * c^d * n^d.
-- So H has polynomial growth of degree at most d.
theorem polynomial_growth_of_finiteIndex [H.FiniteIndex]
    (hG : HasPolynomialGrowth G) : HasPolynomialGrowth H := by
  sorry

/-- Converse direction: if a finite-index subgroup has polynomial growth, so does the group.

This uses that G is covered by finitely many H-cosets, each a translate of H. -/
-- Proof: G = ⋃_{i=1}^{index} H * r_i.
-- So B_G(n) ⊆ ⋃_{i=1}^{index} B_H(n+L) * r_i, where L = max word length of coset reps.
-- Thus |B_G(n)| ≤ index * |B_H(n+L)|.
-- If H has polynomial growth, this gives polynomial growth for G.
theorem polynomial_growth_of_subgroup_finiteIndex [H.FiniteIndex]
    (hH : HasPolynomialGrowth H) : HasPolynomialGrowth G := by
  sorry

end

end Gromov.Schreier.WordBounds
